# Generated by Django 4.1.4 on 2022-12-19 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('horarios', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=5)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico'),
        ),
    ]
