# Generated by Django 4.1.4 on 2023-01-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_cliente_options_alter_cliente_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente'),
            preserve_default=False,
        ),
    ]
