# Generated by Django 4.1.5 on 2023-01-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_alter_agenda_marcado_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
