# Generated by Django 4.1.5 on 2023-01-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_consulta_data_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data_agendamento',
        ),
    ]
